# Generated by Django 4.1.4 on 2023-01-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokuser',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiktokuser',
            name='tiktok_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tiktokuser',
            name='url',
            field=models.URLField(default='', max_length=256),
        ),
    ]
