# Generated by Django 4.1.4 on 2023-01-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTBackend', '0003_product_positivity_tiktokuser_positivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokuser',
            name='avatar',
            field=models.URLField(default='', max_length=256),
        ),
    ]
