# Generated by Django 4.1.4 on 2023-01-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTBackend', '0005_tiktokuser_hashtags_tiktokuser_nouns'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiktokHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(default='', max_length=128)),
                ('points', models.BigIntegerField(default=0)),
            ],
        ),
    ]
