# Generated by Django 4.1.4 on 2023-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTBackend', '0006_tiktokhashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='points',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top1points',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top1post',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top1url',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top2points',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top2post',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top2url',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top3points',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top3post',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top3url',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='positivity',
            field=models.CharField(default='neutral', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
